config/routes.rb
FirehoseApp::Application.routes.draw do

  root 'static_pages#index'
  resources :pics

end

app/models/pic.rb
class Pic < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController

	def index
		@pics = Pic.all
	end

	def new
		@pic = Pic.new
	end

	def create
		Pic.create( pic_params )
		redirect_to pics_path
	end

	private

	def pic_params
		params.require(:pic).permit(:title, :message, :who, :image)
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirehoseApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to 'Blue Ocean', root_path, :class => 'brand' %>
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
        <ul class = "nav">
        	<li>
				<%= link_to 'My App', pics_path %>
        	</li>
        	<li>
        		<%= link_to 'New Pic', new_pic_path %>
        	</li>
      </div>
 
    </div>
  </div>
</div>
<%= yield %>

</body>
</html>

app/views/pics/index.html.erb
<% @pics.each do |pic| %>
	<div class="ice-box span3 text-center text_decoration">
		<h2>
			<u>
			Title: <%= pic.title %>
		</u>
		</h2>

		<%= image_tag pic.image %>
		<h3>
			Message: <%= pic.message %>
		</h3>
		<h3>
		Who: <%= pic.who %>
		</h3>
		<br/>
	</div>
	<% end %>	

app/views/pics/new.html.erb
<div class="ice-box span6 offset3 text-center">
	<h2>Submit Image</h2>
	<%= simple_form_for @pic do |f| %>
		<%= f.input :title %>
		<%= f.input :message %>
		<%= f.input :who %>

		<%= f.input :image %>

		<%= f.submit "Save", :class =>'btn btn-primary btn-large'%>
	<% end %>
</div>

app/views/static_pages/index.html.erb
<div class="span5 offset4 ice-box text-center">
	<h1 class="awesome-sauce">
		The 1980's never ended...
	</h1>

	<br/>

	<h2>
		so get in the water.
	</h2>

	<br/>

	<%=link_to 'Find your Ocean', pics_path, :class =>'btn btn-primary btn-large' %>

</div>